// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '';
const HAS_SUPABASE_CONFIG = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const emptyResult = <T>(data: T | null = null) => ({ data, error: null });

const createNoopQueryBuilder = () => {
  const query = {
    select: () => query,
    eq: () => query,
    maybeSingle: async () => emptyResult(null),
    insert: async () => emptyResult(null),
    update: async () => emptyResult(null),
    delete: () => ({
      eq: async () => emptyResult(null),
    }),
  };

  return query;
};

const createMockSupabaseClient = (): SupabaseClient<Database> => ({
  auth: {
    getSession: async () => ({ data: { session: null }, error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
    signUp: async () => ({ data: { user: null, session: null }, error: null }),
    signInWithPassword: async () => ({ data: { user: null, session: null }, error: null }),
    signOut: async () => ({ error: null }),
    onAuthStateChange: () => ({
      data: {
        subscription: {
          unsubscribe: () => undefined,
        },
      },
    }),
  },
  from: () => createNoopQueryBuilder(),
} as unknown as SupabaseClient<Database>);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = HAS_SUPABASE_CONFIG
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createMockSupabaseClient();